services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dlm-app-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${AIVEN_MYSQL_HOST:-localhost}
      PMA_PORT: ${AIVEN_MYSQL_PORT:-3306}
      PMA_USER: ${AIVEN_MYSQL_USER:-root}
      PMA_PASSWORD: ${AIVEN_MYSQL_PASSWORD:-root}
      PMA_ARBITRARY: ${PMA_ARBITRARY:-0}
      PMA_SSL: ${AIVEN_MYSQL_SSL:-1}
